### DISCUSSION TITLE
Is it possible to link a pluralized string?

### DISCUSSION THREAD

**Discussion by gdurandrexel** [slang-i18n/slang#205] [Q&A] [answered]
I have:
```yaml
string1:
  one: string1
  other: string1s
```
Is there a way to have `string2` referencing a specific value of string1, e.g. `string2: '@:string1.one'` or `string2: '@:string1(1)'`?
