### DISCUSSION TITLE
slang 4.1.0 generates multiple files instead of a single one

### DISCUSSION THREAD

**Discussion by ngoc-quoc-huynh** [slang-i18n/slang#258] [Q&A] [answered]
I'm using the following `build.yaml` configuration. With `slang_flutter: ^3.32.0 ` and `slang_build_runner: ^3.29.0`, running `dart run slang generate` generates a single file: `translations.g.dart`. 
However, updating to `slang_flutter: ^4.1.0` and `slang_build_runner: ^4.1.0` now generates three files: `translations.g.dart`, `translations_de.g.dart`, and `translations_en.g.dart`.

Is this behavior intended in the new version?

```yaml
targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          input_directory: lib/static/i18n
          input_file_pattern: .i18n.yaml
          locale_handling: false
          output_directory: lib/static/i18n
          output_file_name: translations.g.dart
          translation_class_visibility: public
 ```
