### ISSUE TITLE
build_runner does not handle trailing commas in build.yaml

### ISSUE THREAD

**Issue by Tienisto** [slang-i18n/slang#157]
**Describe the bug**
Paths with trailing commas are not handled correctly when using build_runner.

```yaml
targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          input_directory: lib/abc/ # <-- does not work
```
