### ISSUE TITLE
Plurals generator creates wrong strings

### ISSUE THREAD

**Issue by awaik** [slang-i18n/slang#161]
**Describe the bug**
Generator creates wrong plurals strings.

For example I have

```
  "someKey": {
    "apple": {
      "one": "I have $n apple.",
      "other": "I have $n apples."
    }
  },
```
 Run `dart run slang`. It creates file with strings

```
extension on TranslationsEn {
	dynamic _flatMapFunction(String path) {
		switch (path) {
			case 'someKey.apple': return ({required num n}) => (_root.$meta.cardinalResolver ?? PluralResolvers.cardinal('en'))(n,
				one: 'I have \$n apple.',
				other: 'I have \$n apples.',
			);
```

But the correct string is: `one: 'I have $n apple.',` - without backslash.

**Additional context**
Package version slang: ^3.23.0

Doctor:
```
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.0.1 22A400 darwin-arm64, locale en-DE)
    • Flutter version 3.13.2 on channel stable at /Users/mavbook/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (3 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mavbook/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • AwaikSE (mobile) • 00008030-000C74481A3B802E • ios            • iOS 16.1.2 20B110
    • macOS (desktop)  • macos                     • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by Tienisto** [comment]
Can you show me your config?

**Comment by awaik** [comment]
This one


```
targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale

          input_directory: assets/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/i18n
          output_file_name: translations.g.dart
          output_format: multiple_files

          string_interpolation: braces

          enumName: AppLocale

          key_case: camel
          key_map_case: null
          param_case: camel

          flat_map: false

          namespaces: false
          locale_handling: false
          translation_class_visibility: public

          pluralization:
            auto: cardinal
            default_parameter: n

```
