### ISSUE TITLE
Unexpected parenthesis in linked translations with enums

### ISSUE THREAD

**Issue by DaleLaw** [slang-i18n/slang#181]
**Describe the bug**
When using a linked translation in conjunction with an enum linked translation, the former unexpectedly generates parentheses. This leads to a syntax error in the strings.i18n.yaml file, preventing it from being compiled.

```yaml
hello: "Hello"
gender(context=Gender): {
  male: "male",
  female: "female"
}
hello_gender: "@:hello, @:gender"
```
strings.18n.yaml

```dart
String get hello => 'Hello';
String gender({required Gender context}) {
  switch (context) {
    case Gender.male:
      return 'male';
    case Gender.female:
      return 'female';
  }
}
String hello_gender({required Gender context}) => '${_root.hello()}, ${_root.gender(context: context)}';
```
strings.g.dart

**Expected behavior**
It should generate `_root.hello` instead of `_root.hello()`
