### ISSUE TITLE
slang_gpt duplicate keys when there are modifiers

### ISSUE THREAD

**Issue by aureat** [slang-i18n/slang#192]
Hi, I've recently started using slang. And it's a great solution for flutter localization :)

I keep my translations in a yaml format. Whenever there are modifiers in a key, slang_gpt adds the same key both with and without modifiers. Example:

Base Locale:
```yaml
locale(map):
  tr: "Turkish"
  en: "English"
```

Generated:
```yaml
locale(map):
  tr: "Turkish"
  en: "English"
locale:
  tr: "Turkish"
  en: "English"
```

GPT logs show no duplication. The duplication seems to arise when `applyMapRecursive` from `package:slang/src/runner/apply.dart` is called on line `293` in `package:slang_gpt/lib/runner.dart`. 
```dart
      result = applyMapRecursive(
        baseMap: originalTranslations,
        newMap: response.jsonMessage,
        oldMap: result,
        verbose: false,
      );
```

When I call print before and after this line,

Before:
```dart
result = {}
```

After:
```dart
result = {
  test(context=SomeContext): {please: Bitte, clear: Löschen}, 
  test: {please: Bitte, clear: Löschen}
}
```
