### ISSUE TITLE
Setting base_locale

### ISSUE THREAD

**Issue by hantrungkien** [slang-i18n/slang#204]
Hi @Tienisto, I have 2 translate files

`strings_en-US.i18n.json`
`strings_ja-JP.i18n.json`

and `slang.yaml`

```yaml
base_locale: en-US
fallback_strategy: base_locale
input_directory: lib/i18n
input_file_pattern: .i18n.json
output_directory: lib/i18n
output_file_name: strings.g.dart
```

Here is log after run `dart run slang`

```
Scanning translations...

 (base) en-US -> lib/i18n/strings_en-US.i18n.json
        ja-JP -> lib/i18n/strings_ja-JP.i18n.json
```

But here is log after run `dart run build_runner build --delete-conflicting-outputs`

```
Translation file for base locale "en" not found.
```

Could you please share a solution to bypass it? Thanks a lot!
