### ISSUE TITLE
Issue with plural param in yaml and case transformation

### ISSUE THREAD

**Issue by ominibyte** [slang-i18n/slang#253]
**Describe the bug**
I use hyphen to represent word separation and I noticed that when trying to generate plural forms with custom param name, the generator does not generate the correct method signature when using hyphenated words. It only works well when the word is camel case.

**To Reproduce**
slang.yaml
```yaml
base_locale: en
fallback_strategy: base_locale
input_directory: lib/i18n
input_file_pattern: .i18n.yaml
output_directory: lib/i18n
string_interpolation: dart
key_case: camel
key_map_case: camel
```

strings_en.i18n.yaml
```yaml
manage-record:
    timeHours(param=hours):
      one: $hours hour
      other: $hours hours
    time-minutes(param=minutes):
      one: $minutes minute
      other: $minutes minutes
``` 

It generates:

```dart
String timeHours({required num hours}) => (_root.$meta.cardinalResolver ?? PluralResolvers.cardinal('en'))(hours,
		one: '${hours} hour',
		other: '${hours} hours',
	);
	String timeMinutes(param=minutes)({required num n, required Object minutes}) => (_root.$meta.cardinalResolver ?? PluralResolvers.cardinal('en'))(n,
		one: '${minutes} minute',
		other: '${minutes} minutes',
	);
```

**Expected behavior**
The method for `time-minutes` should have similar signature with `timeHours`.

**Additional context**
Right now, I am having to use camel case as a workaround.
