### ISSUE TITLE
Incorrect class_name in code generation for new build & buildSync methods

### ISSUE THREAD

**Issue by Dri3xCz** [slang-i18n/slang#254]
**Describe the bug**
Running `dart run slang` generates output files. These generated output files use by default class 'Translations'. This class name can be changed in build.yaml file. Generated files respect this option in most places but not in the new methods build & buildSync which always tries to return class Translations, which usually doesn't exist unless you specified Translations as the class_name.
 
**To Reproduce**
1. build.yaml
```yaml
targets:
  $default:
    builders:
      slang_build_runner:
        options:
          class_name: Test
```
2. `dart run slang` 

**Expected behavior**
generated_file.g.dart
```dart
Future<Test> build({...
Future<Test> buildSync({...
```
