### ISSUE TITLE
Obfuscation renders NBSP character in Text widget

### ISSUE THREAD

**Issue by ngoc-quoc-huynh** [slang-i18n/slang#259]
**Describe the bug**
Using obfuscation will render the non-breaking space (NBSP) character in unicode if I'm displaying the content e.g. in a Text widget.

**To Reproduce**
1. Create a flutter project
1. Create a translation with this content: `test: 'Some text\u{00A0}…'`
2. Run `dart run slang generate`
3. Create a widget with reference to the translation

**Expected behavior**
The `\u{00A0}` will not be displayed.

**Additional content**

```yaml
# build.yaml
targets:
  $default:
    builders:
      slang_build_runner:
        options:
          input_file_pattern: .i18n.yaml
          obfuscation:
            enabled: true
```

```yaml
# strings.i18n.yaml
test: 'Some text\u{00A0}…'
```

```dart
// Example code
import 'package:flutter/material.dart';
import 'package:untitled/strings.g.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text(AppLocale.en.buildSync().test),
        ),
      ),
    );
  }
}
```

## Screenshots

| ![Normal](https://github.com/user-attachments/assets/37c3cc3a-4f4c-4762-8775-993112b7f804) | ![Obfuscation](https://github.com/user-attachments/assets/824f7700-d805-48e2-bc94-f6f90b0db433) |
|:--:|:--:|
| **Normal** | **Obfuscation** |
