### ISSUE TITLE
fails to generate translations dart file when no namespace is given for secondary locales

### ISSUE THREAD

**Issue by nateshmbhat** [slang-i18n/slang#265]
I have below setup : 

```
Project root : 
  |- translations/
        |- en.json
        |- hi.json
  |- lib/
  |-build.yaml
 ```
 
 ```
slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: translations
          input_file_pattern: .json
          output_directory: lib/translations_generated
          output_file_name: translations.g.dart
          flutter_integration: true
          translate_var: t
          param_case: pascal
          lazy: true
```

It is failing to generate the translation file for "hi.json". It works when i name this file as "strings_hi.json" but doesn't work when i name it just as "hi.json".

**Expected behavior**
It should work regardless of whether i name my file "hi.json" or "strings_hi.json". Right now only "strings_hi.json" works.
