### ISSUE TITLE
Occasionally, the location of the generated code will be wrong

### ISSUE THREAD

**Issue by kjxbyz** [slang-i18n/slang#280]
**Describe the bug**
Occasionally, the location of the generated code will be wrong.

![Image](https://github.com/user-attachments/assets/097c30db-2a2a-4d4d-bd21-6e71eff1a11f)

**To Reproduce**

**Expected behavior**
The location of the generated code is normal.

**Additional context**
```
targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: zh
          fallback_strategy: base_locale
          input_directory: assets/i18n
          output_directory: lib/i18n
          maps:
            - locales

      flutter_gen_runner: # or flutter_gen
        options:
          output: lib/generated/ # Optional (default: lib/gen/)
          line_length: 80
          integrations:
            flutter_svg: true
            rive: true
            lottie: true
          assets:
#            enabled: true
            outputs:
              class_name: AppAssets
              package_parameter_enabled: false
              # Assets.imagesChip
              # style: camel-case

              # Assets.images_chip
              # style: snake-case

              # Assets.images.chip (default style)
              style: dot-delimiter

#            exclude:
#              - assets-extern/*
#              - pictures/chip5.jpg
          fonts:
#            enabled: true
            outputs:
              class_name: AppFontFamily
          colors:
#            enabled: true
            outputs:
              class_name: AppColors
            inputs:
              - assets/color/colors.xml

```
