### ISSUE TITLE
Support int, double, or bool when using interfaces

### ISSUE THREAD

**Issue by kjxbyz** [slang-i18n/slang#288]
**Describe the bug**
interface doesn't work for me. The `i18n_en.g.dart` file not generated.

change 
```
interfaces:
            AppColor: # full config
              paths:
                - colors.*
              attributes:
                - int alpha
                - int red
                - int green
                - int blue
                - String label
```

to
```
interfaces:
            AppColor: # full config
              paths:
                - colors.*
              attributes:
                - int? alpha
                - int? red
                - int? green
                - int? blue
                - String label
```
The `i18n_en.g.dart` file generated. But the type is incorrect.

The type in `AppColor` is correct.
<img width="820" alt="Image" src="https://github.com/user-attachments/assets/beb89247-5e25-437a-9016-ab69321a2db0" />

The type in `_Translations$colors$0i5$It` is incorrect.
<img width="806" alt="Image" src="https://github.com/user-attachments/assets/ae0afd87-444c-4065-9d28-e922b5fa69ff" />

**To Reproduce**

**Expected behavior**

**Additional context**

build.yaml
```
targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: assets/i18n
          output_directory: lib/i18n
          output_file_name: i18n.g.dart
          interfaces:
            AppColor: # full config
              paths:
                - colors.*
              attributes:
                - int alpha
                - int red
                - int green
                - int blue
                - String label
```

assets/i18n/en.i18n.json
```
{
  "colors": [
    {
      "alpha": 255,
      "red": 255,
      "green": 255,
      "blue": 255,
      "label": "White"
    },
    {
      "alpha": 255,
      "red": 158,
      "green": 158,
      "blue": 158,
      "label": "Grey"
    },
    {
      "alpha": 255,
      "red": 0,
      "green": 0,
      "blue": 0,
      "label": "Black"
    },
    {
      "alpha": 255,
      "red": 244,
      "green": 67,
      "blue": 54,
      "label": "Red"
    },
    {
      "alpha": 255,
      "red": 255,
      "green": 152,
      "blue": 0,
      "label": "Orange"
    },
    {
      "alpha": 255,
      "red": 33,
      "green": 150,
      "blue": 243,
      "label": "Blue"
    }
  ]
}
```

**Comment by Tienisto** [comment]
That's because slang is an i18n library. Every leaf is a string.

```yaml
interfaces:
  AppColor:
    paths:
      - colors.*
    attributes:
      - String alpha
      - String red
      - String green
      - String blue
      - String label
```
