### ISSUE TITLE
Support "include" option in config file

### ISSUE THREAD

**Issue by emersonsiega** [slang-i18n/slang#81]
**Motivation**
We have multiple apps (micro apps) using almost the same `build.yaml` file. 
It would be nice if we can have a base file to be used as reference.

[lints package](https://pub.dev/packages/lints#how-to-enable-these-lints) have this feature. It's a nice usage example :)

```yaml
include: package:my_local_package/slang_settings.yaml

targets:
  $default:
    builders:
      slang_build_runner:
          # new settings or overrides
```
